/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cart { 'items' : Array<OrderItem> }
export type ExternalBlob = Uint8Array;
export interface FoodItem {
  'id' : string,
  'name' : string,
  'description' : string,
  'category' : string,
  'image' : [] | [ExternalBlob],
  'price' : bigint,
}
export interface OrderItem { 'quantity' : bigint, 'foodItem' : FoodItem }
export interface OrderType {
  'id' : string,
  'status' : string,
  'userId' : Principal,
  'items' : Array<OrderItem>,
  'totalPrice' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addFoodItem' : ActorMethod<[string, string, bigint, string], string>,
  'addToCart' : ActorMethod<[FoodItem, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearUserCart' : ActorMethod<[], undefined>,
  'deleteFoodItem' : ActorMethod<[string], undefined>,
  'getAllFoodItems' : ActorMethod<[], Array<FoodItem>>,
  'getAllOrders' : ActorMethod<[], Array<OrderType>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Cart>,
  'getFoodItemsByCategory' : ActorMethod<[string], Array<FoodItem>>,
  'getPendingOrders' : ActorMethod<[], Array<OrderType>>,
  'getPreparingOrders' : ActorMethod<[], Array<OrderType>>,
  'getReadyOrders' : ActorMethod<[], Array<OrderType>>,
  'getUserOrders' : ActorMethod<[Principal], Array<OrderType>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[], string>,
  'removeFromCart' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCartItemQuantity' : ActorMethod<[string, bigint], undefined>,
  'updateFoodItem' : ActorMethod<
    [string, string, string, bigint, string],
    undefined
  >,
  'updateFoodItemImage' : ActorMethod<[string, ExternalBlob], undefined>,
  'updateOrderStatus' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];